name: CI
on: [push, pull_request]
jobs:
  tests:
    strategy:
      matrix:
        ruby-version:
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
        rails-version:
          - "7.0"
          - "7.1"
          - "7.2"
          - "8.0"
        exclude:
          - ruby-version: "3.1"
            rails-version: "8.0"
      fail-fast: false
    env:
      BUNDLE_GEMFILE: gemfiles/Gemfile.rails-${{ matrix.rails-version }}

    name: ${{ format('Tests (Ruby {0}) (Rails {1})', matrix.ruby-version, matrix.rails-version) }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bin/test
